apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: image-is-signed-by-github-actions
spec:
# If the following line is uncommented, the usage of unsigned images will be allowed, but with a warning
# mode: warn
  images:
  # All images in the Entando Dockerhub registry (**docker** is a way to include both index.docker.io and registry.hub.docker.com)
  - glob: "**docker**/entando/**"
  authorities:
  - keyless:
      # Signed by the public Fulcio certificate authority
      url: https://fulcio.sigstore.dev
      identities:
      # Matches the Github Actions OIDC issuer
      - issuer: https://token.actions.githubusercontent.com
        # Matches any github workflow from the entando and entando-k8s repositories.
        subjectRegExp: https://github.com/(entando|entando-k8s)/[^/]+/.github/workflows/[^@]+@.*
    ctlog:
      url: https://rekor.sigstore.dev