name: PUB

on:
  push:
    tags:
      - 'v*'

env:
  PPL_TEMPLATE_VERSION: "v2.0.0"
  ENTANDO_BOT_TOKEN: ${{ secrets.ENTANDO_BOT_TOKEN }}
  PR_CHECKER_PATH: ".github/pr-title-checker-config.json"

  # Java/Node versions and build commands that may be needed for building
  # ...
  DOCKER_IMAGE_BASE_NAME: entando/some-entando-repository
  DOCKER_IMAGE_ARCHITECTURE: linux/amd64,linux/arm64
  DOCKER_IMAGE_CONTEXT: .
  DOCKER_IMAGE_FILE: Dockerfile
  DOCKER_IMAGE_PUSH: true

jobs:
  publication:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      # This is needed in order to keyless sign the images with cosign
      id-token: write
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      # Cosign installation
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      # Additional steps to set up Java/Node and run the needed build commands
      # ...

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_IMAGE_BASE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr,value={{base_ref}}
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,event=pr,value={{base_ref}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.DOCKER_IMAGE_ARCHITECTURE }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DOCKER_IMAGE_CONTEXT }}
          file: ${{ env.DOCKER_IMAGE_FILE }}
          push: ${{ env.DOCKER_IMAGE_PUSH }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.DOCKER_IMAGE_ARCHITECTURE }}
      
      # We sign, with the keyless procedure, the pushed image's digest directly, not the tags.
      # As noted here: https://www.chainguard.dev/unchained/zero-friction-keyless-signing-with-github-actions
      # "A common mistake here is to sign the tag you just pushed.  Tags are mutable and can point to different
      # image digests over time, so if you use the tag here you are opening yourself up to both race conditions
      # and malicious actors (incl. the registry!) which could have you sign something other than what you just
      # pushed.  By signing the digest you just pushed, you effectively eliminate the need to trust the registry
      # because you are signing a crypographically verifiable checksum of the image."
      - name: Sign the image
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: cosign sign --yes ${{ env.DOCKER_IMAGE_BASE_NAME }}@${DIGEST}

      # In this version, the verification is included in the publication job, right after the signing

      # In a for loop, each pushed tag is verified using the issued Certificate Identity ("https://github.com/" + the workflow ref)
      # and Certificate OIDC Issuer ("https://token.actions.githubusercontent.com")
      # Note: this can also be done by passing all tags in a single command
      # (e.g. "cosign verify entando/repo:1.0 entando/repo:sha-123 --certificate-identity= ...")
      - name: Cosign verification for each pushed tag
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          WORKFLOW_REF: ${{ github.workflow_ref }}
        run: |
          for tag in $TAGS; do
            echo "Verifying the '$tag' tag with Certificate Identity: 'https://github.com/${WORKFLOW_REF} and Certificate OIDC Issuer: 'https://token.actions.githubusercontent.com'"
            cosign verify "$tag" --certificate-identity="https://github.com/${WORKFLOW_REF}" --certificate-oidc-issuer="https://token.actions.githubusercontent.com" | jq .
          done
          echo "To verify a tag with cosign, launch the command:"
          echo "cosign verify [ORGANIZATION]/[REPOSITORY]:[TAG] --certificate-identity=[CERTIFICATE_IDENTITY] --certificate-oidc-issuer=[CERTIFICATE_OIDC_ISSUER]"