name: Merge any release branch to main
run-name: ${{ github.actor }} has merged a pr in one of the release branches
on:
  pull_request:
    types:
      - closed
    branches:
      - release/*


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Merge release to develop
        run: |
          git pull origin main
          git merge --no-ff ${{ github.event.pull_request.base.ref }}
          git push origin main